In [1]:
print("PIAIC Assignment # 1")

PIAIC Assignment # 1


In [2]:
print("PIAIC131286")

PIAIC131286


In [3]:
print("Tanzeela Siddique")

Tanzeela Siddique


In [4]:
import numpy as np

In [6]:
a = np.array([2,3,4])

In [8]:
a

array([2, 3, 4])

In [9]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
a.reshape(3,-1)

array([[2],
       [3],
       [4]])

In [12]:
arr = np.random.randint(1,11,size=(6, 10))

In [13]:
arr

array([[10,  2,  3, 10,  6,  6,  5,  4,  1,  3],
       [ 4,  5,  7,  7,  1,  9, 10,  4,  2, 10],
       [ 4,  1,  5,  4,  5,  2,  2,  2,  9,  5],
       [ 7,  6,  9,  2,  4,  5,  4,  1, 10,  7],
       [ 1,  1,  9,  8,  6, 10,  4,  8,  9,  2],
       [ 2,  3,  7,  2,  8,  8,  8,  9,  8,  2]])